table Tb_RH
	lineageTag: 7e72c083-dcee-4b68-82aa-419204edfa85

	measure 'total de salarios' = SUM(Tb_RH[SALARIO])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 2838dc81-2408-470a-a3cd-9b93869ecf9f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'total de faltas' = SUM(Tb_RH[QTDE FALTA])
		formatString: 0
		lineageTag: d81b8dd5-524d-4c3f-b443-b4d00a24ebb0

	measure 'idade por genero' = AVERAGE(Tb_RH[IDADE])
		lineageTag: bb019a1c-f9f1-4670-a212-17234e154b25

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure genero = COUNT(Tb_RH[NOME])
		formatString: 0
		lineageTag: 6a8f4399-7c01-4692-be97-57a1842472ce

	column ID
		dataType: int64
		formatString: 0
		lineageTag: c4dd36fb-501a-48e2-b4ab-f6ec3cc244a8
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 1a75bd92-175f-44cf-99b1-1e069f534228
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column IDADE
		dataType: int64
		formatString: 0
		lineageTag: a4cfb2c5-5e5d-4c83-a385-ffedcc34a83b
		summarizeBy: sum
		sourceColumn: IDADE

		annotation SummarizationSetBy = Automatic

	column 'DATA ADIMISSAO'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5eba82f2-75ce-4fbf-b6a2-d4b7132b1ed4
		summarizeBy: none
		sourceColumn: DATA ADIMISSAO

		variation Variation
			isDefault
			relationship: 9172111a-4b09-4e09-bf2b-3dfe97f65a5f
			defaultHierarchy: LocalDateTable_ab19c5e9-a319-4452-932a-f7051e3fade3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DEPARTAMENTO
		dataType: string
		lineageTag: 6b773ca5-5914-40bf-88a9-f7ea4248d622
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column SALARIO
		dataType: int64
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 061d6235-ff29-43c4-8346-86bcb2c2aba0
		summarizeBy: sum
		sourceColumn: SALARIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'QTDE FALTA'
		dataType: int64
		formatString: 0
		lineageTag: aa471438-c7b7-4980-b7e8-122a1f8d95b6
		summarizeBy: sum
		sourceColumn: QTDE FALTA

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: 1863e7b4-6df0-493b-8fe9-04338b2e504d
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column DEMISSOES
		dataType: string
		lineageTag: ae07bff9-8db9-44e5-a742-c7bdbfcdc970
		summarizeBy: none
		sourceColumn: DEMISSOES

		annotation SummarizationSetBy = Automatic

	column SEXO
		dataType: string
		lineageTag: 1f3c679c-16e9-49c3-b8d3-877947d020f5
		summarizeBy: none
		sourceColumn: SEXO

		annotation SummarizationSetBy = Automatic

	column 'CONTRATACÕES FEITAS'
		dataType: int64
		formatString: 0
		lineageTag: a2b088ee-d8a8-4cd4-b85c-b15186e30482
		summarizeBy: sum
		sourceColumn: CONTRATACÕES FEITAS

		annotation SummarizationSetBy = Automatic

	column ANO = YEAR(Tb_RH[DATA ADIMISSAO])
		formatString: 0
		lineageTag: 421fdc63-ff66-4569-8e6a-20016d0496b1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column FUNCIONARIO = IF(Tb_RH[SALARIO] >= 5000, "FUNCIONÁRIO CARO", "FUNCIONARIO COMUM")
		lineageTag: 15e4d314-ffa6-4a97-8acc-f8152f8c3ca4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ESTADO =
			IF(Tb_RH[FILIAL] = "RJ", "RIO DE JANEIRO"
			        ,IF(Tb_RH[FILIAL] = "SP", "SÃO PAULO"
			        ,IF(Tb_RH[FILIAL] = "MG", "MINAS GERAIS")))
		lineageTag: df04189c-68c0-4769-95fe-9d3c625ed8f2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '1 FUNCIONARIO' =
			IF(Tb_RH[SALARIO] >= 5000 &&
			                Tb_RH[DEPARTAMENTO] = "GERENCIA", "FUNCIONA CARO", "FUNCIONARIO COMUM")
		lineageTag: dc9babd5-7b2a-41e7-8a39-29e156c9a59f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'dia da semana' = FORMAT(Tb_RH[DATA ADIMISSAO], "dddd/mmmm/yyyy")
		lineageTag: cb4e88eb-2f88-457e-a6c5-a0a687dd2755
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Tb_RH = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\thiag\OneDrive\Ambiente de Trabalho\Power BI\Modulo 1\Novo_Material_2025\Materiais_Power_BI_Analytics\1_MODULO - POWER_BI - Starter\1_RH\SALARIOS.xlsx"), null, true),
				    Tb_RH_Table = Fonte{[Item="Tb_RH",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tb_RH_Table,{{"ID", Int64.Type}, {"NOME", type text}, {"IDADE", Int64.Type}, {"DATA ADIMISSAO", type date}, {"DEPARTAMENTO", type text}, {"SALARIO", Int64.Type}, {"QTDE FALTA", Int64.Type}, {"FILIAL", type text}, {"DEMISSOES", type text}, {"SEXO", type text}, {"CONTRATACÕES FEITAS", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

